### ISSUE TITLE
Change position of "Time entry has been logged." popup

### ISSUE THREAD

**Issue by AlveBrekXtreme** [rubynor/reap#192]
Right now, the popup is placed right over the time reg button. I think this should be changed because if someone wants to make a new time reg right after creating a time reg, they will need to click on the **x** before making the new time reg.
![image](https://github.com/rubynor/reap/assets/114334244/06219c17-aeeb-407f-8cac-11ac9e8768b3)

**Comment by hoglund003** [comment]
IMO we could just loose this toast. I think seeing the registration has been created/updated and displayed below, it's good enough feedback.
