### ISSUE TITLE
Cannot create/update time registrations while a timer is running

### ISSUE THREAD

**Issue by hoglund003** [rubynor/reap#204]
Users should not be able to start a timer, if another one is running.
But I think users should be able to create/update/destroy different registrations, while another timer is running.

![image](https://github.com/rubynor/reap/assets/29040689/16ac2f76-bf20-4be0-9c7d-38ff414f3dba)

**Comment by mejiaro** [comment]
I agree, some times you need to edit other timers that isn't the one that's running now.
