### ISSUE TITLE
Entry time not updating in real time

### ISSUE THREAD

**Issue by hoglund003** [rubynor/reap#28]
After starting the timer on a time entry, the time time stamp does not update in real time.

![Screen Shot 2024-03-14 at 09 41 49-fullpage](https://github.com/rubynor/reap/assets/29040689/a757e7c7-830e-49aa-8626-5250d3682542)

**Comment by str1fe** [comment]
Are you actively working on this @hoglund003. I sort of gave @Jordybastien the same task :innocent:

**Comment by str1fe** [comment]
Yes, then we're stealing your task @hoglund003. Sorry :innocent: . @Jordybastien: you may continue with it
