### ISSUE TITLE
Start button not working

### ISSUE THREAD

**Issue by str1fe** [rubynor/reap#30]
![Selection_037](https://github.com/rubynor/reap/assets/1814618/07b5309b-978f-47e8-a81c-ee35febf81a0)

**Comment by str1fe** [comment]
Seems i created a duplicate of #28

**Comment by Jordybastien** [comment]
Well noted @str1fe

**Comment by str1fe** [comment]
One thing to add: We should have the «start» button inside the modal here:
![Selection_039](https://github.com/rubynor/reap/assets/1814618/6d4b3351-0745-4b2c-a49b-a82faf08539f)

Similar to what harvest does:
![Selection_038](https://github.com/rubynor/reap/assets/1814618/268d185d-8c2b-4b1f-bbd3-d95765908bd3)

**Comment by Jordybastien** [comment]
> One thing to add: We should have the «start» button inside the modal here: ![Selection_039](https://private-user-images.githubusercontent.com/1814618/312905331-6d4b3351-0745-4b2c-a49b-a82faf08539f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzE1NTQsIm5iZiI6MTcxMDQzMTI1NCwicGF0aCI6Ii8xODE0NjE4LzMxMjkwNTMzMS02ZDRiMzM1MS0wNzQ1LTRiMmMtYTQ5Yi1hODJmYWYwODUzOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTU0NzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODA4NTg4NjA5N2EzOTNiNjJiZTEzZTExZjM3ODMxZTk4ZDBhZGRhNzU3YmZmODBmOTU3NGI5MDkyMGM2NzJlYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ogo7BaLcQDCMdHNt89NtiHaKI5uvE9lEgMTf6Jqas7o)
> 
> Similar to what harvest does: ![Selection_038](https://private-user-images.githubusercontent.com/1814618/312905391-268d185d-8c2b-4b1f-bbd3-d95765908bd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzE1NTQsIm5iZiI6MTcxMDQzMTI1NCwicGF0aCI6Ii8xODE0NjE4LzMxMjkwNTM5MS0yNjhkMTg1ZC04YzJiLTRiMWYtYmJkMy1kOTU3NjU5MDhiZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTU0NzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTM5ZWFkMzZiZmU0NTI2M2YwYWIyNmZmZmI5ZDM4ODk2YmFhNGVlYTI5ZjRiOTI3MWEzOTA0OTAzYWUxN2UwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bGxRcEiMeZXtWLy-2SKsF6LY_hTTXWOX7r8uudEZbhk)

It basically replaces the `create Time reg` btn right @str1fe ?

**Comment by str1fe** [comment]
Yes, but only if you have not written anything in the hour/minute input field. If you have written hours and minutes, then `create Time reg` button can be shown instead
